API/urls.py
from django.urls import path, include
from .views import UserList,  UserDetail,  CryptoList, CryptoDetail, api_manual


app_name = 'API'


urlpatterns = [
    path('', api_manual, name='main'),
    path('crypto/', CryptoList.as_view(), name='crypto_list'),
    path('crypto/<slug:slug>/', CryptoDetail.as_view(), name='crypto_detail'),
    path('user/', UserList.as_view(), name='user_list'),
    path('user/<int:pk>', UserDetail.as_view(), name='user'),
]

articles/urls.py
from django.urls import path
from .views import ArticleListView, update

app_name = 'articles'
urlpatterns = [
    path('', ArticleListView.as_view() , name ='articles' ),
    path('update/', update, name = 'update')

]

crypto/urls.py
from django.contrib import admin
from django.urls import path, include
from data import  views
from django.shortcuts import redirect
from django.views.generic import RedirectView

urlpatterns = [
    path('blog_api-auth/', include('rest_framework.urls')),
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(pattern_name= 'data:data')),
    path('data/', include('data.urls')),
    path('users/', include('users.urls')),
    path('articles/', include('articles.urls')),
    path('API/', include('API.urls'))

]

data/urls.py
from django.urls import path
from .views import data_list_view, favourite_list_view ,update,CryptoDetailView, add_to_favourite_list, remove_from_favourite_list
app_name = 'data'
urlpatterns = [
    path('', data_list_view, name='data'),
    path('list/', favourite_list_view, name='favourite_list'),
    path('update/', update, name='update'),
    path('detail/<int:pk>', CryptoDetailView.as_view(), name = 'crypto_detail'),
    path('detail/add/<int:pk>' , add_to_favourite_list , name = 'add_to_fav'),
    path('detail/remove/<int:pk>' , remove_from_favourite_list , name = 'remove_from_fav'),

]

users/urls.py
from django.urls import path
from .views import register, login, log_out

app_name = 'users'

urlpatterns = [
    path('login/', login, name='login'),
    path('register/', register, name='register'),
    path('logout/', log_out, name='logout'),
]

data/models.py
from django.db import models
from django.contrib.auth.models import User, AbstractUser


class Crypto(models.Model):
    name = models.CharField(max_length=30, unique=True)
    slug = models.CharField(max_length=15)
    total_supply = models.BigIntegerField( null=True )
    price = models.PositiveBigIntegerField( null=True )
    market_cap = models.PositiveBigIntegerField(null=True)
    volume_change_24h = models.FloatField( null=True)
    percent_change_24h = models.FloatField(null=True)
    user_favourite = models.ManyToManyField(
        User, related_name='favourite')

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['-name', 'price']
        indexes = [
            models.Index(fields=['name', 'slug'])
        ]

data/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from .utils import parse_data_from_api
from .models import Crypto
from django.contrib.auth.models import User
from django.core.paginator import Paginator, EmptyPage, \
    PageNotAnInteger
from django.urls import reverse
from django.views.generic import DetailView


class CryptoDetailView(DetailView):
    model = Crypto
    template_name = 'data/detail_view.html'
    context_object_name = 'crypto'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        isAdded = False
        context['user'] = ''
        is_log_user = self.request.user.is_authenticated
        if is_log_user:
            if self.object in self.request.user.favourite.all():
                isAdded = True
            user = self.request.user.username
            context['isAdded'] = isAdded
            context['user'] = user
        return context


def data_list_view(request):
    # проверка юзера на аутентификацию
    if request.user.is_authenticated:
        user = request.user.username
    else:
        user = ''
    # обработка сортировки
    if request.GET.get('sort'):
        sort_by = request.GET.get('sort')

    else:
        sort_by = 'price'
    if sort_by != 'name':
        crypto_list = Crypto.objects.all().order_by(f'-{sort_by}')
    else:
        crypto_list = Crypto.objects.all().order_by(f'{sort_by}')

    # обработка поисковой строки
    if request.GET.get('search_query'):
        search_query = request.GET.get('search_query')
        crypto_list = Crypto.objects.filter(
            name__istartswith=search_query) | Crypto.objects.filter(
            slug__istartswith=search_query).order_by('name')
        return render(request, 'data/data.html',
                      {'data': crypto_list, 'user': user})

    # пагинация данных
    paginator = Paginator(crypto_list, 8)
    page_number = request.GET.get('page', 1)
    try:
        data = paginator.page(page_number)
    except PageNotAnInteger:
        data = paginator.page(1)
    except EmptyPage:
        data = paginator.page(paginator.num_pages)
    return render(request, 'data/data.html', {'data': data, 'user': user})


def favourite_list_view(request):
    data = ''
    if request.user.is_authenticated:
        user_name = request.user.username
        user_object = User.objects.get(username=user_name)
        if user_object.favourite.all().select_related():
            data = user_object.favourite.all().select_related()
    else:

        return HttpResponseRedirect(reverse('data:data'))
    context = {'data': data, 'user': user_name}
    return render(request, 'data/list.html', context=context)


def add_to_favourite_list(request, pk):
    crypto_object = Crypto.objects.get(pk=pk)
    user_object = User.objects.get(username=request.user.username)
    user_object.favourite.add(crypto_object)
    return HttpResponseRedirect(reverse('data:favourite_list'))


def remove_from_favourite_list(request, pk):
    crypto_object = Crypto.objects.get(pk=pk)
    user_object = User.objects.get(username=request.user.username)
    user_object.favourite.remove(crypto_object)
    return HttpResponseRedirect(reverse('data:favourite_list'))


def update(request):
    parse_data_from_api()
    return HttpResponseRedirect(reverse('data:data'))

data/templates/data/data.html
{% extends 'data/layout.html' %}
{% load static %}
<head>
    <meta charset="UTF-8">
    <title>crypto </title>
    <link type="text/css" href="{% static 'css/style.css' %}" rel="stylesheet"/>

</head>

{% block user %}

    {% if user %}
        <a href='{% url 'users:logout' %}'>logout {{ user }}</a>
    {% else %}
        <a class="lin" href="{% url 'users:login' %}"> log in </a>
    {% endif %}
{% endblock %}


{% block favourite %}
    {% if user %}
        <a class="lin" href="{% url 'data:favourite_list' %}"> избранные </a>
    {% endif %}
{% endblock %}


{% block content %}
    <div id = 'tabl'>
        <form class='search' method="GET" action="{% url 'data:data' %}?search_query=search_query ">
            <input type="text" name="search_query" placeholder="Поиск...">
            <button type="submit">Найти</button>
        </form>

        <table class="table">
            <caption><a href="{% url 'data:update' %}">ОБНОВИТЬ ДАННЫЕ ↓</a></caption>
            <tr>
                <th><a href="{% url 'data:data' %}?sort=name">Название</a></th>
                <th><a href="{% url 'data:data' %}?sort=slug">Символ</a></th>
                <th><a href="{% url 'data:data' %}?sort=total_supply">кол-во монет</a></th>
                <th><a href="{% url 'data:data' %}?sort=price">Цена $</a></th>
                <th><a href="{% url 'data:data' %}?sort=market_cap"> Капитализация</a></th>
                <th><a href="{% url 'data:data' %}?sort=percent_change_24h"> Суточные изменения %</a></th>
            </tr>
            {% for i in data %}
                <tr>
                    <td><a href="{% url 'data:crypto_detail' i.id %}">{{ i.name }}</a></td>
                    <td>{{ i.slug }}</td>
                    <td>{{ i.total_supply }}</td>
                    <td>{{ i.price }}</td>
                    <td>{{ i.market_cap }}</td>
                    <td>{{ i.percent_change_24h }}</td>
                </tr>
            {% endfor %}

        </table>
    </div>

    <div class="pagination">
 <span class="step-links">
 {% if data.has_previous %}
     <a href="?page={{ data.previous_page_number }}{% if request.GET.sort %}&sort={{ request.GET.sort }}{% endif %}">Previous</a>
 {% endif %}
     <span class="current">
 Page {{ data.number }} of {{ data.paginator.num_pages }}.
 </span>
     {% if data.has_next %}
         <a href="?page={{ data.next_page_number }}{% if request.GET.sort %}&sort={{ request.GET.sort }}{% endif %}">Next</a>
     {% endif %}
 </span>
    </div>

{% endblock %}

data/templates/data/detail_view.html
{% extends 'data/layout.html' %}
{% load static %}


{% block user %}
    {% if user %}
        <a href='{% url 'users:logout' %}'>logout {{ user }}</a>
    {% else %}
        <a class="lin" href="{% url 'users:login' %}"> log in </a>
    {% endif %}
{% endblock %}


{% block content %}
    <div>
        <table class="table">
            <tr>
                <th>Название</th>
                <th>Символ</th>
                <th>кол-во монет</th>
                <th>Цена</th>
                <th>Капитализация</th>
                <th>Суточные изменения %</th>
            </tr>
            <tr>
                <td>{{ crypto.name }}</td>
                <td>{{ crypto.slug }}</td>
                <td>{{ crypto.total_supply }}</td>
                <td>{{ crypto.price }}</td>
                <td>{{ crypto.market_cap }}</td>
                <td>{{ crypto.percent_change_24h }}</td>
            </tr>
        </table>


        {% if user %}

            {% if isAdded %}
                <p>вы уже отслеживаете данную валюту</p>
                <a href="{% url 'data:remove_from_fav' crypto.id %}"> удалить из избранных </a>

            {% else %}

                <p>вы не отслеживаете данную валюту</p>
                <a href="{% url 'data:add_to_fav' crypto.id %}"> добавить в избранное</a>

            {% endif %}

        {% else %}

            <p>чтобы добавить валюту в список избранных вам нужно зарегистрироваться </p>

        {% endif %}
        <br>
        <br>
        <a href='{% url 'data:data' %}'>вернуться на главную</a>
    </div>
{% endblock %}

data/templates/data/layout.html
{% load static %}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>crypto </title>
    <link type="text/css" href="{% static 'css/style.css' %}" rel="stylesheet"/>

</head>
<body class="bod">


<header>
    <a class='lin' href="{% url 'data:data' %}"><h1> Crypto Currency </h1></a>
    <nav>
        {% block article %}<a class="lin" href="{% url 'articles:articles' %}"> Articles </a> {% endblock %}
        <a class="lin" href="{% url 'API:main' %}"> {API} </a>
        <a class="lin" href="{% url 'users:login' %}"> {% block user %}  log in {% endblock %} </a>
        <a class="lin" href="{% url 'users:register' %}"> register </a>
        {% block favourite %}{% endblock %}

    </nav>
</header>
<div class="content">

    {% block content %}
    {% endblock content %}

</div>

</body>
</html>

data/templates/data/list.html
{% extends 'data/layout.html' %}
{% load static %}


{% block user %}
    {% if user %}
        <a href='{% url 'users:logout' %}'>logout {{ user }}</a>
    {% else %}
        <a class="lin" href="{% url 'users:login' %}"> log in </a>
    {% endif %}
{% endblock %}


{% block content %}
    <div>
        <table class="table">
            <tr>
                <th>Название</th>
                <th>Символ</th>
                <th>кол-во монет</th>
                <th>Цена</th>
                <th>Капитализация</th>

                <th>Суточные изменения %</th>
            </tr>

            {% if data %}

                {% for i in data %}

                    <tr>
                        <td><a href="{% url 'data:crypto_detail' i.id %}">{{ i.name }}</a></td>
                        <td>{{ i.slug }}</td>
                        <td>{{ i.total_supply }}</td>
                        <td>{{ i.price }}</td>
                        <td>{{ i.market_cap }}</td>
                        <td>{{ i.percent_change_24h }}</td>
                    </tr>

                {% endfor %}

            {% endif %}

        </table>
        <a href="{% url 'data:data' %}">вернуться на главную</a>
    </div>
{% endblock %}