API/urls.py
from django.urls import path, include
from .views import UserList,  UserDetail,  CryptoList, CryptoDetail, api_manual


app_name = 'API'


urlpatterns = [
    path('', api_manual, name='main'),
    path('crypto/', CryptoList.as_view(), name='crypto_list'),
    path('crypto/<slug:slug>/', CryptoDetail.as_view(), name='crypto_detail'),
    path('user/', UserList.as_view(), name='user_list'),
    path('user/<int:pk>', UserDetail.as_view(), name='user'),
]

articles/urls.py
from django.urls import path
from .views import ArticleListView, update

app_name = 'articles'
urlpatterns = [
    path('', ArticleListView.as_view() , name ='articles' ),
    path('update/', update, name = 'update')

]

crypto/urls.py
from django.contrib import admin
from django.urls import path, include
from data import  views
from django.shortcuts import redirect
from django.views.generic import RedirectView

urlpatterns = [
    path('blog_api-auth/', include('rest_framework.urls')),
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(pattern_name= 'data:data')),
    path('data/', include('data.urls')),
    path('users/', include('users.urls')),
    path('articles/', include('articles.urls')),
    path('API/', include('API.urls'))

]

articles/models.py
from django.db import models


class Article(models.Model):
    name = models.CharField(max_length=200)
    url = models.URLField()

    class Meta:
        ordering = ['name']
        indexes = [
            models.Index(fields=['name'])
        ]

    def __str__(self):
        return self.name
    
    

articles/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse

from .utils import parse_articles
from django.views.generic import ListView
from .models import Article


class ArticleListView(ListView):
    model = Article
    template_name = 'articles/articles.html'
    context_object_name = 'data'


def update(request):
    parse_articles()
    return HttpResponseRedirect(reverse('articles:articles'))

articles/templates/articles/articles.html
{% extends 'data/layout.html' %}
{% load static %}

{% block article %}<a class="lin" href="{% url 'data:data' %}"> Crypto </a> {% endblock %}

{% block content %}
<div class="articles" id="art">
    <table class="table">
        <caption><a href="{% url 'articles:update' %}">обновить список статей ↓</a></caption>
        <tr>
            <th>Самые Актуальные статьи из Мира Криптовалют</th>
        </tr>
        {% for i in data %}
            <tr>
                <td><a href="{{ i.url }}">{{ i.name }}</a></td>

            </tr>
        {% endfor %}

    </table>
</div>

{% endblock %}